# to run in terminal $ make
CC = gcc

# All needed .c files (source files, excluding header files)
SRC_CODE = driver.c lex.c parser.c vm.c

#################################

# default rule

all: $(SRC_CODE)
	$(CC) $(SRC_CODE) -lm



